"""tags

Revision ID: 9b3fe93be3b3
Revises: 6bfcd3cb283a
Create Date: 2020-11-16 13:47:48.070415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3fe93be3b3'
down_revision = '6bfcd3cb283a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('polltag',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('tag_title', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['tag_title'], ['tag.title'], ),
    sa.PrimaryKeyConstraint('poll_id', 'tag_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polltag')
    op.drop_table('tag')
    # ### end Alembic commands ###
